server:
  profiles: dev

hertz:
  address: ":18080"
  enablePprof: true
  enableGzip: true
  enableAccessLog: true
  logLevel: info
  logFileName: "log/hertz.log"
  logMaxSize: 10
  logMaxAge: 3
  logMaxBackups: 50

mysql:
  host: "127.0.0.1"
  port: 3306
  db: "weflow"
  username: "root"
  password: "root"
  charset: "utf8"
  dsn: "root:root@tcp(127.0.0.1:3306)/weflow?charset=utf8&parseTime=True&loc=Local"

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

mongo:
  address: "127.0.0.1:27017"
  username: ""
  password: ""

#雪花算法配置
snowflake:
  #雪花计算方法,（1-漂移算法|2-传统算法），默认1
  method: 1
  #基础时间（ms单位），不能超过当前系统时间
  baseTime: 1582136402000
  #机器码，必须由外部设定，最大值 2^WorkerIdBitLength-1
  workerId: 1
  #机器码位长，默认值6，取值范围 [1, 15]（要求：序列数位长+机器码位长不超过22）
  bitLength: 6
  #序列数位长，默认值6，取值范围 [3, 21]（要求：序列数位长+机器码位长不超过22）
  seqBitLength: 6
