hertz:
  address: ":18080"
  enable_pprof: true
  enable_gzip: true
  enable_access_log: true
  log_level: info
  log_file_name: "log/hertz.log"
  log_max_size: 10
  log_max_age: 3
  log_max_backups: 50

mysql:
  host: "127.0.0.1"
  port: 3306
  db: "weflow"
  username: "root"
  password: "root"
  charset: "utf8"
  dsn: "root:root@tcp(127.0.0.1:3306)/weflow?charset=utf8&parseTime=True&loc=Local"

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0

mongo:
  address: "127.0.0.1:27017"
  username: ""
  password: ""
